### ISSUE TITLE
About FPS and FLOPs

### ISSUE THREAD

**Issue by imcjx** [ybarancan/BEV_feat_stitch#13]
Thank you for your great work, we would like to cite your paper for comparison.
When we use titanxp GPU for testing, only 1.2fps does not match the 21fps written in the paper, where did I go wrong. What is the flops of this model, I calculated it is about 2900G, is this normal?

**Comment by ybarancan** [comment]
Between which operations did you calculate the runtime? And in order to maximize the speed, we used an implementation that uses the already processed frames rather than repeatedly processing them. So for each estimation, only one frame is processed since the others already passed through the backbone in the previous iteration. This allows for batching where you can get 5 samples' outputs in one pass. Through this, we achieved the reported FPS. That implementation needs significant polishing to push to github and in the future, if I find time, I will push it. But for now make sure that the time measurement does not include saving results, metric calculations and data loading. I didn't calculate FLOPS but if the number you gave is for N frames used for one output, you can divide it by N to get the optimized implementation FLOPS.

**Comment by imcjx** [comment]
Thank you very much for your answer
